title                    : "Glenn Sarti (DEV)"
url                      : ""
port                     : 4000

show_drafts: true
future: true

sass:
  style:            :expanded

# Analytics
analytics:
  provider               : false  # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
