version: 1.0.{build}
branches:
  except:
  - dev
build_script:
- cmd: >-
    ECHO Setting Ruby 2.2 as default
    SET PATH=C:\Ruby22-x64\bin;%PATH%

    ECHO Getting ruby version...
    ruby -v

    bundle install --path .bundle\gems

    ECHO Contents of Gemfile.lock
    type Gemfile.Lock

    bundle exec rake clean build:prod
test: off